print("Введи 4 стадии становления человека:")
perv = (input("Первая стадия:"))
vtor = (input("Вторая стадия:"))
tret = (input("Третья стадия:"))
chet = (input("Четвертая стадия:"))
print("Твой ответ:")
print(perv, vtor, tret, chet, sep = "=>")
